# Generated by Django 3.1.3 on 2021-02-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('code', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Код изделия')),
                ('image', models.ImageField(blank=True, default='', upload_to='goods/', verbose_name='Фотография изделия')),
                ('weight_clean', models.FloatField(default=0, verbose_name='Вес чистой детали')),
                ('norma_with_carpet', models.IntegerField(default=0, verbose_name='Норма с ковром')),
                ('consumption_smesi', models.IntegerField(default=0, verbose_name='Расход смеси')),
                ('one_person_norma', models.IntegerField(default=0, verbose_name='Норма на одного человека')),
                ('two_person_norma', models.IntegerField(default=0, verbose_name='Норма на двух чловек')),
                ('defect_limit', models.FloatField(default=0, verbose_name='Лимит брака')),
                ('min_temperature', models.IntegerField(default=0, verbose_name='Минимальная температура')),
                ('max_temperature', models.IntegerField(default=0, verbose_name='Максимальная температура')),
                ('min_malt', models.IntegerField(default=0, verbose_name='Минимальная выдержка')),
                ('max_malt', models.IntegerField(default=0, verbose_name='Максимальная выдержка')),
                ('min_pressure', models.IntegerField(default=0, verbose_name='Минимальное давление')),
                ('max_pressure', models.IntegerField(default=0, verbose_name='Максимальное давление')),
                ('min_strength', models.IntegerField(default=0, verbose_name='Минимальная твердость')),
                ('max_strength', models.IntegerField(default=0, verbose_name='Максимальная твердость')),
                ('url', models.SlugField(default='goods_', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='UnitsMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('url', models.SlugField(default='unit_', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='GoodsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate', models.CharField(max_length=150, verbose_name='Название(дубликат)')),
                ('cleaning_period', models.FloatField(verbose_name='Период чистки')),
                ('number_nest', models.FloatField(verbose_name='Номер гнезда')),
                ('percent_mass', models.IntegerField(verbose_name='Процент массы')),
                ('url', models.SlugField(blank=True, max_length=150)),
                ('code_goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.goods', verbose_name='Код изделия')),
            ],
            options={
                'verbose_name': 'Форма изделия',
                'verbose_name_plural': 'Формы изделий',
            },
        ),
        migrations.CreateModel(
            name='GoodsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text="Вписывать только месяц и год, день оставлть '01' ", verbose_name='Месяц')),
                ('lith', models.IntegerField(verbose_name='Отлито шт.')),
                ('remote', models.IntegerField(verbose_name='Брак шт.')),
                ('remote_percent', models.FloatField(verbose_name='Брак %')),
                ('one_man_sr', models.CharField(max_length=150, verbose_name='Смена выработки на 1 человека в СРЕДНЕМ')),
                ('one_man_max', models.CharField(max_length=150, verbose_name='Смена выработки на 1 человека МАКСИМАЛЬНО')),
                ('two_man_sr', models.CharField(max_length=150, verbose_name='Смена выработки на 2 человек в СРЕДНЕМ')),
                ('two_man_max', models.CharField(max_length=150, verbose_name='Смена выработки на 2 человека МАКСИМАЛЬНО')),
                ('code_goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.goods', verbose_name='Код изделия')),
            ],
            options={
                'verbose_name': 'Календарь изделий',
                'verbose_name_plural': 'Календарь изделий',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='measurement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='prokes.unitsmeasurement', verbose_name='Единицы измерения'),
        ),
    ]
