# Generated by Django 3.1.3 on 2021-03-15 13:50

from django.db import migrations, models
import django.db.models.deletion
import prokes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя заказчика')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('representative', models.CharField(max_length=100, verbose_name='Представитель (ФИО)')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, verbose_name='Код изделия')),
                ('name', models.CharField(max_length=30, verbose_name='Название изделия')),
                ('image', models.ImageField(blank=True, upload_to='goods/', verbose_name='Фотография изделия')),
                ('weight_clean', models.FloatField(default=0, verbose_name='Вес чистой детали')),
                ('norma_na_vigruzku', models.FloatField(default=0, verbose_name='Норма на выгрузку')),
                ('rashod_smesi', models.FloatField(default=0, verbose_name='Расход смеси')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, verbose_name='Код смеси')),
                ('weight', models.IntegerField(verbose_name='Вес смеси')),
                ('batch_number', models.IntegerField(verbose_name='Номер партии')),
                ('pallet_number', models.IntegerField(verbose_name='Номер поддона')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Nariad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Номер наряда')),
                ('value', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата')),
                ('consumption', models.IntegerField(verbose_name='Расход смеси')),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.goods', verbose_name='Код изделия')),
                ('material_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.materials', verbose_name='Код смеси')),
            ],
            options={
                'verbose_name': 'Наряд',
                'verbose_name_plural': 'Наряды',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование поставщика')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(default='+7', max_length=11, verbose_name='Номер телефона')),
                ('representative', models.CharField(max_length=100, verbose_name='Представитель (ФИО)')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код сотрудника')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(default='+7', max_length=11, verbose_name='Номер телефона')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('salary', models.PositiveIntegerField(help_text='Вводить в рублях', verbose_name='Оклад')),
                ('fired', models.BooleanField(default=False, verbose_name='Уволен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='OTK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_value', models.IntegerField(verbose_name='Количество хороших изделий')),
                ('remote_value', models.IntegerField(verbose_name='Количество бракованных изделий')),
                ('date', models.DateField(verbose_name='Дата проверки')),
                ('nariad_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.nariad', verbose_name='Код изделия')),
            ],
            options={
                'verbose_name': 'ОТК',
                'verbose_name_plural': 'ОТК',
            },
        ),
        migrations.AddField(
            model_name='nariad',
            name='worker_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.workers', verbose_name='Код сотрудника'),
        ),
        migrations.CreateModel(
            name='MaterialStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата проверки')),
                ('material_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.materials', verbose_name='Код смеси')),
            ],
            options={
                'verbose_name': 'Склад материалов',
                'verbose_name_plural': 'Склады материалов',
            },
        ),
        migrations.CreateModel(
            name='GoodsStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Количество')),
                ('OTK_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.otk', verbose_name='Код ОТК')),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.customer', verbose_name='Код заказчика')),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.goods', verbose_name='Код изделия')),
            ],
            options={
                'verbose_name': 'Склад изделий',
                'verbose_name_plural': 'Склады изделий',
            },
        ),
        migrations.CreateModel(
            name='GoodsDefaultForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate', models.CharField(max_length=150, verbose_name='Дубликат')),
                ('cleaning_period', models.FloatField(verbose_name='Период чистки')),
                ('number_nest', models.FloatField(verbose_name='Номер гнезда формы')),
                ('percent_mass', models.IntegerField(verbose_name='Процент массы')),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokes.goods', verbose_name='Код изделия')),
            ],
            options={
                'verbose_name': 'Форма изделия',
                'verbose_name_plural': 'Формы изделий',
            },
        ),
        migrations.CreateModel(
            name='GoodsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text="Вписывать только месяц и год, день оставлть '01' ", verbose_name='Месяц')),
                ('lith', models.IntegerField(verbose_name='Отлито шт.')),
                ('remote', models.IntegerField(verbose_name='Брак шт.')),
                ('remote_percent', models.FloatField(verbose_name='Брак %')),
                ('one_man_sr', models.CharField(max_length=150, verbose_name='Смена выработки на 1 человека в СРЕДНЕМ')),
                ('one_man_max', models.CharField(max_length=150, verbose_name='Смена выработки на 1 человека МАКСИМАЛЬНО')),
                ('two_man_sr', models.CharField(max_length=150, verbose_name='Смена выработки на 2 человек в СРЕДНЕМ')),
                ('two_man_max', models.CharField(max_length=150, verbose_name='Смена выработки на 2 человека МАКСИМАЛЬНО')),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokes.goods', verbose_name='Код изделия')),
            ],
            options={
                'verbose_name': 'Календарь изделий',
                'verbose_name_plural': 'Календарь изделий',
            },
        ),
        migrations.CreateModel(
            name='DeliveriesMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=prokes.models.default_datetime, verbose_name='Дата заказа')),
                ('values', models.IntegerField(verbose_name='Количество')),
                ('code_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokes.materials', verbose_name='Код смеси')),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokes.suppliers', verbose_name='Имя поставщика')),
            ],
            options={
                'verbose_name': 'Дата поставки',
                'verbose_name_plural': 'Даты поставок',
            },
        ),
        migrations.CreateModel(
            name='CheckoutGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=prokes.models.default_datetime, verbose_name='Дата заказа')),
                ('values', models.IntegerField(verbose_name='Количество')),
                ('code_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokes.goods', verbose_name='Код изделия')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokes.customer', verbose_name='Имя заказчика')),
            ],
            options={
                'verbose_name': 'Дата заказа',
                'verbose_name_plural': 'Даты заказов',
            },
        ),
    ]
