# Generated by Django 3.1.3 on 2021-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutgoods',
            name='order_goods',
        ),
        migrations.RemoveField(
            model_name='checkoutgoods',
            name='order_goods_values',
        ),
        migrations.AddField(
            model_name='checkoutgoods',
            name='order',
            field=models.TextField(default='', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
