# Generated by Django 3.2 on 2021-05-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstorage',
            name='supplier_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prokes.suppliers', verbose_name='Код поставщика'),
            preserve_default=False,
        ),
    ]
