# Generated by Django 3.1.3 on 2021-02-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.unitsmeasurement', verbose_name='Единицы измерения'),
        ),
    ]
