# Generated by Django 3.2 on 2021-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsstorage',
            name='date',
        ),
        migrations.AddField(
            model_name='goodsstorage',
            name='customer_checkout',
            field=models.ManyToManyField(to='prokes.CheckoutGoods', verbose_name='Дата заказа'),
        ),
    ]
