# Generated by Django 3.1.3 on 2021-03-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdefaultform',
            name='goods_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_forms', to='prokes.goods', verbose_name='Код изделия'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
