# Generated by Django 3.1.3 on 2021-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0002_auto_20210217_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, upload_to='goods/', verbose_name='Фотография изделия'),
        ),
    ]
