# Generated by Django 3.2 on 2021-04-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0002_auto_20210430_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsstorage',
            name='customer_checkout',
            field=models.ManyToManyField(to='prokes.CheckoutGoods', verbose_name='Заказ №'),
        ),
    ]
