# Generated by Django 3.1.3 on 2021-02-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0002_goodscalendar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscalendar',
            name='url',
        ),
    ]
