# Generated by Django 3.1.3 on 2021-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0002_auto_20210219_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код сотрудника')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('salary', models.PositiveIntegerField(help_text='Вводить в рублях', verbose_name='Оклад')),
                ('standard_time', models.IntegerField(verbose_name='Норма времени')),
                ('lose_time', models.IntegerField(verbose_name='Пропущенно времени')),
                ('cof_proisvod', models.IntegerField(help_text='Указывать в процентах', verbose_name='Коэфициент производительности')),
                ('fired', models.BooleanField(default=False, verbose_name='Уволен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
