# Generated by Django 3.1.3 on 2021-02-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0003_auto_20210217_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscalendar',
            name='code_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokes.goods', verbose_name='Код изделия'),
        ),
    ]
