# Generated by Django 3.1.3 on 2021-02-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0003_auto_20210223_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Suppliers',
        ),
    ]
