# Generated by Django 3.2 on 2021-04-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0003_alter_goodsstorage_customer_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsstorage',
            name='customer_checkout',
        ),
        migrations.AddField(
            model_name='goodsstorage',
            name='customer_checkout',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='prokes.checkoutgoods', verbose_name='Заказ №'),
            preserve_default=False,
        ),
    ]
