# Generated by Django 3.1.3 on 2021-02-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0004_auto_20210223_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutgoods',
            old_name='customer_name',
            new_name='supplier_name',
        ),
    ]
