# Generated by Django 3.2 on 2021-04-30 12:41

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0004_auto_20210430_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsstorage',
            name='customer_goods_value',
        ),
        migrations.AlterField(
            model_name='goodsstorage',
            name='customer_checkout',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='goods_code', chained_model_field='customer_code', on_delete=django.db.models.deletion.CASCADE, to='prokes.checkoutgoods'),
        ),
    ]
