# Generated by Django 3.2 on 2021-05-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0004_auto_20210528_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsstorage',
            name='customer_checkout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prokes.checkoutgoods', verbose_name='Код заказа'),
        ),
    ]
