# Generated by Django 3.2 on 2021-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0005_alter_goodsstorage_customer_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsstorage',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
