# Generated by Django 3.2 on 2021-05-29 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0006_alter_goodsstorage_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorage',
            name='supplier_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prokes.suppliers', verbose_name='Код поставщика'),
        ),
    ]
