# Generated by Django 3.2 on 2021-04-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0008_alter_goodsstorage_customer_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsstorage',
            name='OTK_code',
        ),
    ]
