# Generated by Django 3.2 on 2021-04-30 13:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0009_remove_goodsstorage_otk_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsstorage',
            name='customer_checkout',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='customer_code', chained_model_field='goods_code', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='prokes.checkoutgoods'),
        ),
    ]
