# Generated by Django 3.2 on 2021-05-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0012_alter_goodsstorage_customer_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsstorage',
            name='customer_checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prokes.checkoutgoods', verbose_name='Код заказа'),
        ),
    ]
