# Generated by Django 3.2 on 2021-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokes', '0013_alter_goodsstorage_customer_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutgoods',
            name='date',
            field=models.DateField(default='', verbose_name='Дата заказа'),
        ),
    ]
