# Generated by Django 3.1.3 on 2021-01-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remote',
            name='number',
        ),
        migrations.RemoveField(
            model_name='unitsmeasurement',
            name='unit',
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitsmeasurement',
            name='url',
            field=models.SlugField(default='unit_', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='fired',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
        migrations.AddField(
            model_name='workers',
            name='photo',
            field=models.ImageField(default='', upload_to='workers/', verbose_name='Фотография сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='url',
            field=models.SlugField(default='customer_', max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='goods',
            name='measurement',
        ),
        migrations.AddField(
            model_name='goods',
            name='measurement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prokesh.unitsmeasurement', verbose_name='Единицы измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='url',
            field=models.SlugField(default='goods_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='remote',
            name='code_goods',
            field=models.ManyToManyField(blank=True, to='prokesh.Goods', verbose_name='Код изделия'),
        ),
        migrations.AlterField(
            model_name='remote',
            name='code_smesi',
            field=models.ManyToManyField(blank=True, to='prokesh.Smesi', verbose_name='Код смеси'),
        ),
        migrations.RemoveField(
            model_name='remote',
            name='measurement',
        ),
        migrations.AddField(
            model_name='remote',
            name='measurement',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='prokesh.unitsmeasurement', verbose_name='Единицы измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remote',
            name='url',
            field=models.SlugField(default='remote_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='smesi',
            name='url',
            field=models.SlugField(default='smesi_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='url',
            field=models.SlugField(default='supplier_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='unitsmeasurement',
            name='short_unit',
            field=models.CharField(max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='url',
            field=models.SlugField(default='worker_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='worker_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prokesh.workers', verbose_name='ФИО сотрудника'),
        ),
    ]
