# Generated by Django 3.1.3 on 2021-01-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
