# Generated by Django 3.1.3 on 2021-01-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0002_auto_20210118_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ФИО'),
        ),
    ]
