# Generated by Django 3.1.3 on 2021-01-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0002_auto_20210128_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='code_goods',
        ),
        migrations.AddField(
            model_name='customers',
            name='code_goods',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='prokesh.goods', verbose_name='Код изделия'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='remote',
            name='code_goods',
        ),
        migrations.AddField(
            model_name='remote',
            name='code_goods',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='prokesh.goods', verbose_name='Код изделия'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='remote',
            name='code_smesi',
        ),
        migrations.AddField(
            model_name='remote',
            name='code_smesi',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='prokesh.smesi', verbose_name='Код смеси'),
            preserve_default=False,
        ),
    ]
