# Generated by Django 3.1.3 on 2021-01-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0004_auto_20210118_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='url',
            field=models.SlugField(default='customer_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='url',
            field=models.SlugField(default='goods_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='remote',
            name='url',
            field=models.SlugField(default='remote_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='smesi',
            name='url',
            field=models.SlugField(default='smesi_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='url',
            field=models.SlugField(default='supplier_', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='url',
            field=models.SlugField(default='worker_', max_length=150, unique=True),
        ),
    ]
