# Generated by Django 3.1.3 on 2021-01-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0005_auto_20210118_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remote',
            name='number',
        ),
    ]
