# Generated by Django 3.1.3 on 2021-01-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0006_auto_20210128_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='photo',
            new_name='image',
        ),
    ]
