# Generated by Django 3.1.3 on 2021-02-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0007_auto_20210128_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smesi',
            name='worker_name',
        ),
        migrations.AddField(
            model_name='smesi',
            name='worker_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='prokesh.workers', verbose_name='ФИО сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='url',
            field=models.SlugField(default='worker_', help_text='Не забудьте добавить запись в таблицу Время работы сотрудника!', max_length=150, unique=True),
        ),
    ]
