# Generated by Django 3.1.3 on 2021-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='fired',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
    ]
