# Generated by Django 3.1.3 on 2021-01-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0008_workers_fired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitsmeasurement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='measurement',
        ),
        migrations.AddField(
            model_name='goods',
            name='measurement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prokesh.unitsmeasurement', verbose_name='Единицы измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unitsmeasurement',
            name='short_unit',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='Сокращение'),
        ),
    ]
