# Generated by Django 3.1.3 on 2021-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0008_auto_20210201_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='date',
            field=models.DateField(blank=True, default='', verbose_name='Дата поставки'),
        ),
    ]
