# Generated by Django 3.1.3 on 2021-01-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0009_auto_20210122_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsmeasurement',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='measurement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prokesh.unitsmeasurement', verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='unitsmeasurement',
            name='short_unit',
            field=models.CharField(default='', max_length=10, verbose_name='Сокращение'),
        ),
    ]
