# Generated by Django 3.1.3 on 2021-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0010_auto_20210122_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='measurement',
        ),
        migrations.AddField(
            model_name='goods',
            name='measurement',
            field=models.ManyToManyField(to='prokesh.UnitsMeasurement', verbose_name='Единицы измерения'),
        ),
    ]
