# Generated by Django 3.1.3 on 2021-01-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0012_remove_goods_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remote',
            name='measurement',
        ),
    ]
