# Generated by Django 3.1.3 on 2021-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prokesh', '0013_remove_remote_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='measurement',
            field=models.ManyToManyField(to='prokesh.UnitsMeasurement', verbose_name='Единицы измерения'),
        ),
        migrations.AddField(
            model_name='remote',
            name='measurement',
            field=models.ManyToManyField(to='prokesh.UnitsMeasurement', verbose_name='Единицы измерения'),
        ),
    ]
